global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "nginx"
    static_configs:
      - targets: [ "nginx-exporter:9113" ]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
